// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqzr4XmYcNjotQ1m6dQZyyfCF-qlX2LY',
    appId: '1:917247708333:web:01276cbd31c4b582df4a24',
    messagingSenderId: '917247708333',
    projectId: 'tracker-flutter-8c0f5',
    authDomain: 'tracker-flutter-8c0f5.firebaseapp.com',
    storageBucket: 'tracker-flutter-8c0f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXDHIwZgpf5VOYo8d8wih35Wt-F3ZSG8',
    appId: '1:917247708333:android:b3384a5f99674c22df4a24',
    messagingSenderId: '917247708333',
    projectId: 'tracker-flutter-8c0f5',
    storageBucket: 'tracker-flutter-8c0f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJ3c_aE56UNgb-K9lpCVT0DuxNXdmnq0',
    appId: '1:917247708333:ios:76e52760f260a8d5df4a24',
    messagingSenderId: '917247708333',
    projectId: 'tracker-flutter-8c0f5',
    storageBucket: 'tracker-flutter-8c0f5.firebasestorage.app',
    iosBundleId: 'com.omarmegzari.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRJ3c_aE56UNgb-K9lpCVT0DuxNXdmnq0',
    appId: '1:917247708333:ios:76e52760f260a8d5df4a24',
    messagingSenderId: '917247708333',
    projectId: 'tracker-flutter-8c0f5',
    storageBucket: 'tracker-flutter-8c0f5.firebasestorage.app',
    iosBundleId: 'com.omarmegzari.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrqzr4XmYcNjotQ1m6dQZyyfCF-qlX2LY',
    appId: '1:917247708333:web:ade13906d5832ea6df4a24',
    messagingSenderId: '917247708333',
    projectId: 'tracker-flutter-8c0f5',
    authDomain: 'tracker-flutter-8c0f5.firebaseapp.com',
    storageBucket: 'tracker-flutter-8c0f5.firebasestorage.app',
  );
}
